name: pr_check

on:
  workflow_dispatch:
  push:
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@main
    - name: Enable cache
      uses: DeterminateSystems/magic-nix-cache-action@main
    - name: Lint
      run: nix flake check -L
    - name: Build
      run: nix build -L
