name: pr_check

on:
  workflow_dispatch:
  push:
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
        targets: x86_64-unknown-linux-gnu,wasm32-unknown-unknown
        components: clippy,rustfmt
    - name: Install trunk
      uses: jetli/trunk-action@v0.1.0
      with:
        version: 'latest'

    - name: Lint
      run: cargo clippy
    - name: Check format
      run: cargo fmt --check
    - name: Build frontend
      run: trunk build csgsi_fe/index.html
    - name: Build backend
      run: cargo build -p csgsi_be
